---
- name: Remove successfully created clusterpair and associated resources
  hosts: localhost
  gather_facts: no

  pre_tasks:
  - include_tasks:
      file: "{{ playbook_dir }}/tasks/setup.yaml"
      apply:
        tags:
        - setup
    loop: "{{ clusters }}"
    loop_control:
      loop_var: setup_cluster
    tags:
    - setup

  - name: Delete the clusterpair
    kubernetes.core.k8s:
      kubeconfig: "{{ item.kubeconfig }}"
      context: "{{ item.context }}"
      state: absent
      api_version: stork.libopenstorage.org/v1alpha1
      kind: ClusterPair
      name: "{{ clusterpair_name }}"
      namespace: "{{ admin_namespace }}"
    loop: "{{ cluster_configs }}"

  - name: Delete the objectstorelocation
    kubernetes.core.k8s:
      kubeconfig: "{{ item.kubeconfig }}"
      context: "{{ item.context }}"
      state: absent
      api_version: stork.libopenstorage.org/v1alpha1
      kind: BackupLocation
      name: "{{ clusterpair_name }}"
      namespace: "{{ admin_namespace }}"
    loop: "{{ cluster_configs }}"

  - name: Delete the secret
    kubernetes.core.k8s:
      kubeconfig: "{{ item.kubeconfig }}"
      context: "{{ item.context }}"
      state: absent
      api_version: v1
      kind: Secret
      name: "{{ clusterpair_name }}"
      namespace: "{{ admin_namespace }}"
    loop: "{{ cluster_configs }}"
