
  - name: Get current context if empty
    ansible.builtin.command: kubectl config current-context --kubeconfig {{ setup_cluster.kubeconfig }}
    register: context_result
    when: setup_cluster.context | default('') == ''
    changed_when: false
    tags:
    - setup
  
  - name: set cluster fact
    set_fact:
      cluster_tmp:
        name: "{{ setup_cluster.name }}"
        kubeconfig: "{{ setup_cluster.kubeconfig }}"
        context: "{{ context_result.stdout }}"
        kubeconfig_path: "{{ playbook_dir }}/pxdr-sa-{{ setup_cluster.name | default('cluster_a') }}-kubeconfig.yaml"
    when: setup_cluster.context | default('') == ''

  - name: set cluster fact
    set_fact:
      cluster_tmp:
        name: "{{ setup_cluster.name }}"
        kubeconfig: "{{ setup_cluster.kubeconfig }}"
        context: "{{ setup_cluster.context }}"
        kubeconfig_path: "{{ playbook_dir }}/{{ setup_cluster.name | default('cluster_a') }}-kubeconfig.yaml"
    when: setup_cluster.context | default('') != ''

  - name: Set cluster if not default
    set_fact:
      cluster_configs: "{{ cluster_configs | default([]) + [cluster_tmp]}}"
    tags:
    - setup
